### ISSUE TITLE
`packdiff -p "repo" params` doesn't work 

### ISSUE THREAD

**Issue by rugwirobaker** [duxum/packdiff#1]
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main()

```

**Comment by duxum** [comment]
Can I see the command you used?

**Comment by rugwirobaker** [comment]
`packdiff -p github.com/rugwirobaker/structure v-0.2-middleware v-0.3-store`

**Comment by duxum** [comment]
Looks like an error was being handled late, but now the problem is fixed. #19917b8
